server {
    listen 80;
    listen [::]:80;

    server_name telemetry.stoxla.in;
    root /var/www/lidotelemetry/current/public;
    index index.php index.html;

    access_log /var/log/nginx/lidotelemetry.access.log;
    error_log /var/log/nginx/lidotelemetry.error.log;

    client_max_body_size 10m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
